### ISSUE TITLE
Change country

### ISSUE THREAD

**Issue by enrico-stack** [sundios/Google-rank-tracker#5]
I was trying to change the country to .es instead of .com in the search string but I don't get any rankings back. Do I have to change something else?

**Comment by JamesSimpson** [comment]
Possibly due to GDPR - Google has a popup that has an acceptance button to then bring back search results. 

Any EU country will have this issue (along with UK).

**Comment by sundios** [comment]
Hello @enrico-stack,

Are you running this from your local machine? and are you based in Spain? if so, it should work with the .com or .es. If you are trying to run this through a server and want to check ranks on another location e.g server is in the UK and you want to check ES, then I suggest the use of proxies for the specific location.

I haven't add the possibility of proxies but its an easy and quick fix on the script. Let me know if this is the case and I can add it as an enhancement

@JamesSimpson Im not quite sure if this will be a problem, since we are not using selenium or chromium to open the session. So pop up might never show up. But I might be wrong. I guess if I add the proxy setting I can test.

Thanks

**Comment by enrico-stack** [comment]
I'm based in Germany on a local machine looking for the .es results with Crawlera set as proxy.

**Comment by sundios** [comment]
It should work unless the proxy you are using is banned by Google. Sometimes the proxy services use proxies that already have been banned from Google. So Proxy rotation is highly recommendable. 

Try testing your proxy with selenium. Maybe it's showing a captcha or something.
